tyrano.plugin.kag={version:450,tyrano:null,kag:null,sound_swf:null,is_rider:false,cache_html:{},cache_scenario:{},config:{defaultStorageExtension:"jpg",projectID:"tyranoproject",game_version:"0.0",preload:"on",skipSpeed:"30",patch_apply_auto:"true",mediaFormatDefault:"ogg",configSave:"webstorage"},define:{TYRANO_ENGINE_VERSION:400,"BASE_DIV_NAME":"tyrano_base",FLAG_APRI:false,"www":""},variable:{sf:{},tf:{}},tmp:{checking_macro:false,ready_audio:false,audio_context:false,num_anim:0,map_bgm:{},map_se:{},
sleep_game:null,sleep_game_next:false,base_scale:1,is_se_play:false,is_se_play_wait:false,is_vo_play:false,is_vo_play_wait:false,is_bgm_play:false,is_bgm_play_wait:false,is_audio_stopping:false,loading_make_ref:false,wait_id:"",map_chara_talk_top:{},video_playing:false},stat:{msg:{fix:true,x:0,y:-0.5,z:2,time:600},hand:{visible:true,color:"0x33CCFF"},map_label:{},map_macro:{},vertical:"false",f:{},mp:{},is_stop:false,is_wait:false,is_trans:false,is_wait_anim:false,is_strong_stop:false,strong_stop_recover_index:0,
is_nowait:false,current_message_str:"\u30b2\u30fc\u30e0\u30b9\u30bf\u30fc\u30c8",current_save_str:"",current_keyframe:"",map_keyframe:{},is_script:false,buff_script:"",is_html:false,map_html:{},cssload:{},save_img:"",stack:{"if":[],"call":[],"macro":[]},set_text_span:false,current_scenario:"first.ks",is_skip:{},is_auto:{},current_bgm:"",current_bgm_vol:"",current_se:{},load_auto_next:false,enable_keyconfig:true,current_bgmovie:{storage:"",volume:""},current_camera:{},current_camera_layer:"",current_line:0,
is_hide_message:false,is_click_text:false,is_adding_text:false,flag_ref_page:false,ruby_str:"",ch_speed:"",skip_link:"true",log_join:"false",log_clear:false,f_chara_ptext:"false",flag_glyph:"false",current_cursor:"auto",font:{enable:false,color:"",bold:"",size:"",face:"",italic:""},locate:{x:0,y:0},default_font:{color:"",bold:"",size:"",face:"",italic:"",edge:"",shadow:""},sysview:{save:"./tyrano/html/save.html",load:"./tyrano/html/load.html",backlog:"./tyrano/html/backlog.html",menu:"./tyrano/html/menu.html"},
chara_talk_focus:"none",chara_brightness_value:"60",chara_blur_value:"2",chara_talk_anim:"none",chara_talk_anim_time:230,chara_talk_anim_value:30,apply_filter_str:"",video_stack:null,is_wait_bgmovie:false,charas:{},jcharas:{},play_bgm:true,play_se:true,map_se_volume:{},map_bgm_volume:{},map_vo:{vobuf:{},vochara:{}},vostart:false,log_write:true,buff_label_name:"",already_read:false,visible_menu_button:false,title:""},init:function(){this.kag=this;var that=this;this.tyrano.test();this.parser.loadConfig(function(map_config){that.config=
$.extend(true,that.config,map_config);that.init_game()});$("script").each(function(){if($(this).attr("src"))if($(this).attr("src").indexOf("cordova")!=-1||$(this).attr("src").indexOf("phonegap")!=-1)that.define.FLAG_APRI=true});if(typeof TyranoPlayer=="function")this.tmp.ready_audio=true;var AudioContext=window.AudioContext||window.webkitAudioContext||false;if(AudioContext)this.tmp.audio_context=new AudioContext;try{var browser=$.getBrowser()}catch(e){console.log(e)}},evalScript:function(str){var TG=
this;var f=this.stat.f;var sf=this.variable.sf;var tf=this.variable.tf;var mp=this.stat.mp;eval(str);this.saveSystemVariable();if(this.kag.is_rider)this.kag.rider.pushVariableGrid()},embScript:function(str,preexp){var f=this.stat.f;var sf=this.variable.sf;var tf=this.variable.tf;var mp=this.stat.mp;return eval(str)},saveSystemVariable:function(){$.setStorage(this.kag.config.projectID+"_sf",this.variable.sf,this.kag.config.configSave)},clearVariable:function(){this.stat.f={};this.variable.sf={};this.clearTmpVariable();
this.saveSystemVariable()},clearTmpVariable:function(){var tmp_sys=this.kag.variable.tf["system"];this.kag.variable.tf={};this.kag.variable.tf["system"]=tmp_sys},pushStack:function(name,flag){this.stat.stack[name].push(flag)},popStack:function(name){return this.stat.stack[name].pop()},getStack:function(name){return this.stat.stack[name][this.stat.stack[name].length-1]},setStack:function(name,flag){this.stat.stack[name][this.stat.stack[name].length-1]=flag},endStorage:function(){var pm=this.kag.getStack("call");
if(pm==null)return false;this.kag.popStack("call");this.kag.ftag.nextOrderWithIndex(pm.index,pm.storage)},init_game:function(){var that=this;this.parser=object(tyrano.plugin.kag.parser);this.parser.kag=that;this.ftag=object(tyrano.plugin.kag.ftag);this.ftag.kag=that;this.ftag.init();this.layer=object(tyrano.plugin.kag.layer);this.layer.kag=that;this.layer.init();this.key_mouse=object(tyrano.plugin.kag.key_mouse);this.key_mouse.kag=that;this.key_mouse.init();this.event=object(tyrano.plugin.kag.event);
this.event.kag=that;this.event.init();var tmpsf=$.getStorage(this.kag.config.projectID+"_sf",that.config.configSave);if(tmpsf==null)this.variable.sf={};else this.variable.sf=eval("("+tmpsf+")");this.variable.sf["system"]={};this.variable.tf["system"]={};this.variable.tf["system"]["backlog"]=[];this.stat.default_font.color=$.convertColor(this.kag.config.defaultChColor);this.stat.default_font.bold=$.convertBold(this.kag.config.defaultBold);this.stat.default_font.size=this.kag.config.defaultFontSize;
this.stat.default_font.face=this.kag.config.userFace;this.kag.stat.font=$.extend(true,$.cloneObject(this.kag.stat.font),this.stat.default_font);this.setTitle(this.config["System.title"]);if(this.kag.config["debugMenu.inspector"]=="true")$("#vr").attr("inspector","url:https://aframe.io/releases/0.3.0/aframe-inspector.min.js");if(this.kag.config["autoEnterVR"]=="true")document.addEventListener("click",customEnterVR);var first_scenario_file="first.ks";if($("#first_scenario_file").size()>0)first_scenario_file=
$("#first_scenario_file").val();this.loadScenario(first_scenario_file,function(array_tag){that.ftag.buildTag(array_tag)})},pushBackLog:function(str,type){if(this.stat.log_write==false)return;type=type||"add";var max_back_log=parseInt(this.kag.config["maxBackLogNum"]);if(max_back_log<1)return;if(this.kag.stat.log_clear==true){type="add";this.kag.stat.log_clear=false}if(type=="join"){var index=this.variable.tf.system.backlog.length-1;if(index>=0){var tmp=this.variable.tf["system"]["backlog"][index];
this.variable.tf["system"]["backlog"][this.variable.tf.system.backlog.length-1]=tmp+str}else this.variable.tf["system"]["backlog"].push(str)}else this.variable.tf["system"]["backlog"].push(str);this.stat.current_save_str=this.variable.tf["system"]["backlog"][this.variable.tf.system.backlog.length-1];if(max_back_log<this.variable.tf["system"]["backlog"].length)this.variable.tf["system"]["backlog"].shift()},setTitle:function(title){this.stat.title=title;document.title=title},pushAnimStack:function(){this.kag.tmp.num_anim++},
cutTimeWithSkip:function(time){if(this.kag.stat.is_skip==true)if(this.kag.config.skipEffectIgnore=="true")return 70;return time},readyAudio:function(){if($.userenv()!="pc"){var pm={loop:"false",storage:"",stop:"true"};if(!this.tmp.map_bgm[0]){this.kag.ftag.startTag("playse",pm);this.kag.ftag.startTag("playbgm",pm)}var bgm_slot=parseInt(this.kag.config.defaultBgmSlotNum);var se_slot=parseInt(this.kag.config.defaultSoundSlotNum);for(var i=1;i<bgm_slot;i++){pm.buf=i;if(this.tmp.map_bgm[pm.buf])this.kag.ftag.startTag("playbgm",
pm)}for(var i=1;i<se_slot;i++){pm.buf=i;if(!this.tmp.map_se[pm.buf])this.kag.ftag.startTag("playse",pm)}}},setCursor:function(cursor){this.stat.current_cursor=cursor;if(cursor==="default")$("body").css("cursor","auto");else $("body").css("cursor","url(./data/image/"+cursor+"),default")},popAnimStack:function(){if(this.kag.tmp.num_anim>0)this.kag.tmp.num_anim--;if(this.kag.tmp.num_anim<=0)if(this.kag.stat.is_wait_anim==true){this.kag.stat.is_wait_anim=false;this.kag.layer.showEventLayer();this.kag.ftag.nextOrder()}},
loadScenario:function(file_name,call_back){var that=this;this.stat.is_strong_stop=true;this.stat.current_scenario=file_name;var file_url="";if($.isHTTP(file_name))file_url=file_name;else file_url="./data/scenario/"+file_name;if(that.cache_scenario[file_url]){if(call_back){var result_obj=that.cache_scenario[file_url];var tag_obj=result_obj.array_s;var map_label=result_obj.map_label;that.stat.map_label=map_label;that.stat.is_strong_stop=false;call_back(tag_obj)}}else $.loadText(file_url,function(text_str){var result_obj=
that.parser.parseScenario(text_str);that.cache_scenario[file_url]=result_obj;var tag_obj=result_obj.array_s;var map_label=result_obj.map_label;that.stat.map_label=map_label;that.stat.is_strong_stop=false;if(call_back)call_back(tag_obj)})},checkMessage:function(jtext){if(this.stat.set_text_span==true){jtext.find("p").find(".current_span").removeClass("current_span");this.stat.set_text_span=false}if(jtext.find(".current_span").length==0)jtext.find("p").append($("<span class='current_span'></span>"))},
appendMessage:function(jtext,str){jtext.find("p").find(".current_span").html(str)},preload:function(src,callbk){var that=this;$("<img />").attr("src",src).load(function(e){if(callbk)callbk()}).error(function(e){that.kag.error("\u753b\u50cf\u30d5\u30a1\u30a4\u30eb\u300c"+src+"\u300d\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\u5834\u6240\u306f\u30d5\u30eb\u30d1\u30b9\u3067\u6307\u5b9a\u3055\u308c\u3066\u3044\u307e\u3059\u304b\uff1f (\u4f8b)data/fgimage/file.png");if(callbk)callbk()})},preloadAll:function(storage,
callbk){var that=this;if(typeof storage=="object"&&storage.length>=0){if(storage.length==0){callbk();return}var sum=0;for(var i=0;i<storage.length;i++)that.kag.preload(storage[i],function(){sum++;if(storage.length==sum)callbk()})}else this.kag.preload(pm.storage,function(){callbk()})},setStyles:function(j_obj,array_style){for(key in array_style)if(array_style[key])if(array_style[key]=="");else j_obj.css(key,array_style[key]);return j_obj},html:function(html_file_name,data,callback){var that=this;
data=data||{};if(this.cache_html[html_file_name]){if(callback){var tmpl=$.templates(this.cache_html[html_file_name]);var html=tmpl.render(data);callback($(html))}}else{if(!this.kag.stat.sysview){this.kag.stat.sysview={};this.kag.stat.sysview={save:"./tyrano/html/save.html",load:"./tyrano/html/load.html",backlog:"./tyrano/html/backlog.html",menu:"./tyrano/html/menu.html"}}var path_html=this.kag.stat.sysview[html_file_name];$.loadText(path_html,function(text_str){var tmpl=$.templates(text_str);var html=
tmpl.render(data);that.cache_html[html_file_name]=text_str;if(callback)callback($(html))})}},error:function(str){if(this.kag.config["debugMenu.visible"]=="true"){var current_storage=this.kag.stat.current_scenario;var line=parseInt(this.kag.stat.current_line)+1;var err="Error:"+current_storage+":"+line+"\u884c\u76ee:"+str;$.error_message(err)}},warning:function(str){if(this.kag.config["debugMenu.visible"]=="true")alert(str)},log:function(obj){if(this.kag.config["debugMenu.visible"]=="true")console.log(obj)},
test:function(){}};tyrano.plugin.kag.tag={};
