tyrano.plugin.kag.ftag={tyrano:null,kag:null,array_tag:[],master_tag:{},current_order_index:-1,init:function(){for(var order_type in tyrano.plugin.kag.tag){this.master_tag[order_type]=object(tyrano.plugin.kag.tag[order_type]);this.master_tag[order_type].kag=this.kag}},buildTag:function(array_tag,label_name){this.array_tag=array_tag;if(label_name)this.nextOrderWithLabel(label_name);else this.nextOrderWithLabel("")},buildTagIndex:function(array_tag,index,auto_next){this.array_tag=array_tag;this.nextOrderWithIndex(index,
undefined,undefined,undefined,auto_next)},completeTrans:function(){this.kag.stat.is_trans=false;if(this.kag.stat.is_stop==true){this.kag.layer.showEventLayer();this.nextOrder()}},hideNextImg:function(){},showNextImg:function(){},nextOrder:function(){this.kag.layer.layer_event.hide();var that=this;if(this.kag.stat.is_strong_stop==true)return false;if(this.kag.stat.is_adding_text==true)return false;try{this.current_order_index++;if(this.array_tag.length<=this.current_order_index){this.kag.endStorage();
return false}var tag=$.cloneObject(this.array_tag[this.current_order_index]);this.kag.stat.current_line=tag.line;if(this.kag.is_rider){tag.ks_file=this.kag.stat.current_scenario;this.kag.rider.pushConsoleLog(tag)}else{this.kag.log("**:"+this.current_order_index+"\u3000line:"+tag.line);this.kag.log(tag)}if(tag.name=="call"&&tag.pm.storage=="make.ks"||this.kag.stat.current_scenario=="make.ks"){if(this.kag.stat.flag_ref_page==true){this.kag.tmp.loading_make_ref=true;this.kag.stat.flag_ref_page=false}}else if(this.kag.stat.flag_ref_page==
true){this.kag.stat.flag_ref_page=false;this.kag.stat.log_clear=true;this.kag.ftag.hideNextImg()}if(this.checkCond(tag)!=true){this.nextOrder();return}if(this.kag.stat.is_hide_message==true){this.kag.layer.showMessageLayers();this.kag.stat.is_hide_message=false}if(this.master_tag[tag.name]){tag.pm=this.convertEntity(tag.pm);var err_str=this.checkVital(tag);if(this.master_tag[tag.name].log_join)this.kag.stat.log_join="true";else if(tag.name=="text");else this.kag.stat.log_join="false";if(this.checkCw(tag))this.kag.layer.layer_event.show();
if(err_str!="")this.kag.error(err_str);else{if(tag.pm["z"])tag.pm["z"]=parseFloat(tag.pm["z"])*-1;this.master_tag[tag.name].start($.extend(true,$.cloneObject(this.master_tag[tag.name].pm),tag.pm))}}else if(this.kag.stat.map_macro[tag.name]){tag.pm=this.convertEntity(tag.pm);var pms=tag.pm;var map_obj=this.kag.stat.map_macro[tag.name];var back_pm={};back_pm.index=this.kag.ftag.current_order_index;back_pm.storage=this.kag.stat.current_scenario;back_pm.pm=pms;this.kag.stat.mp=pms;this.kag.pushStack("macro",
back_pm);this.kag.ftag.nextOrderWithIndex(map_obj.index,map_obj.storage)}else{$.error_message($.lang("tag")+"\uff1a["+tag.name+"]"+$.lang("not_exists"));this.nextOrder()}}catch(e){console.log(e);that.kag.error($.lang("error_occurred"))}},checkCw:function(tag){var master_tag=this.master_tag[tag.name];if(master_tag.cw)if(this.kag.stat.is_script!=true&&this.kag.stat.is_html!=true&&this.kag.stat.checking_macro!=true)return true;else return false;else return false},nextOrderWithTag:function(target_tags){try{this.current_order_index++;
var tag=this.array_tag[this.current_order_index];if(this.checkCond(tag)!=true);if(target_tags[tag.name]=="")if(this.master_tag[tag.name]){switch(tag.name){case "elsif":case "else":case "endif":var root=this.kag.getStack("if");if(!root||tag.pm.deep_if!=root.deep)return false}tag.pm=this.convertEntity(tag.pm);this.master_tag[tag.name].start($.extend(true,$.cloneObject(this.master_tag[tag.name].pm),tag.pm));return true}else return false;else return false}catch(e){console.log(this.array_tag);return false}},
convertEntity:function(pm){var that=this;if(pm["*"]=="")pm=$.extend(true,this.kag.stat.mp,$.cloneObject(pm));for(key in pm){var val=pm[key];var c="";if(val.length>0)c=val.substr(0,1);if(val.length>0&&c==="&")pm[key]=this.kag.embScript(val.substr(1,val.length));else if(val.length>0&&c==="%"){var map_obj=this.kag.getStack("macro");if(map_obj)pm[key]=map_obj.pm[val.substr(1,val.length)];var d=val.split("|");if(d.length==2)if(map_obj.pm[$.trim(d[0]).substr(1,$.trim(d[0]).length)])pm[key]=map_obj.pm[$.trim(d[0]).substr(1,
$.trim(d[0]).length)];else pm[key]=$.trim(d[1])}}return pm},checkVital:function(tag){var master_tag=this.master_tag[tag.name];var err_str="";if(master_tag.vital);else return"";var array_vital=master_tag.vital;for(var i=0;i<array_vital.length;i++)if(tag.pm[array_vital[i]]){if(tag.pm[array_vital[i]]=="")err_str+="\u30bf\u30b0\u300c"+tag.name+"\u300d\u306b\u30d1\u30e9\u30e1\u30fc\u30bf\u30fc\u300c"+array_vital[i]+"\u300d\u306f\u5fc5\u9808\u3067\u3059\u3000\n"}else err_str+="\u30bf\u30b0\u300c"+tag.name+
"\u300d\u306b\u30d1\u30e9\u30e1\u30fc\u30bf\u30fc\u300c"+array_vital[i]+"\u300d\u306f\u5fc5\u9808\u3067\u3059\u3000\n";return err_str},checkCond:function(tag){var pm=tag.pm;if(pm.cond){var cond=pm.cond;return this.kag.embScript(cond)}else return true},startTag:function(name,pm){this.master_tag[name].start($.extend(true,$.cloneObject(this.master_tag[name].pm),pm))},nextOrderWithLabel:function(label_name,scenario_file){this.kag.stat.is_strong_stop=false;if(label_name){if(label_name.indexOf("*")!=-1)label_name=
label_name.substr(1,label_name.length);this.kag.ftag.startTag("label",{"label_name":label_name,"nextorder":"false"})}if(label_name=="*savesnap"){var tmpsnap=this.kag.menu.snap;var co=tmpsnap.current_order_index;var cs=tmpsnap.stat.current_scenario;this.nextOrderWithIndex(co,cs,undefined,undefined,"snap");return}var that=this;var original_scenario=scenario_file;label_name=label_name||"";scenario_file=scenario_file||this.kag.stat.current_scenario;label_name=label_name.replace("*","");if(scenario_file!=
this.kag.stat.current_scenario&&original_scenario!=null){this.kag.layer.hideEventLayer();this.kag.loadScenario(scenario_file,function(array_tag){that.kag.layer.showEventLayer();that.kag.ftag.buildTag(array_tag,label_name)})}else if(label_name==""){this.current_order_index=-1;this.nextOrder()}else if(this.kag.stat.map_label[label_name]){var label_obj=this.kag.stat.map_label[label_name];this.current_order_index=label_obj.index;this.nextOrder()}else{$.error_message($.lang("label")+"\uff1a'"+label_name+
"'"+$.lang("not_exists"));this.nextOrder()}},nextOrderWithIndex:function(index,scenario_file,flag,insert,auto_next){this.kag.stat.is_strong_stop=false;this.kag.layer.showEventLayer();var that=this;flag=flag||false;auto_next=auto_next||"yes";scenario_file=scenario_file||this.kag.stat.current_scenario;if(scenario_file!=this.kag.stat.current_scenario||flag==true){this.kag.layer.hideEventLayer();this.kag.loadScenario(scenario_file,function(tmp_array_tag){var array_tag=$.extend(true,[],tmp_array_tag);
if(typeof insert=="object")array_tag.splice(index+1,0,insert);that.kag.layer.showEventLayer();that.kag.ftag.buildTagIndex(array_tag,index,auto_next)})}else{this.current_order_index=index;if(auto_next=="yes")this.nextOrder();else if(auto_next=="snap"){this.kag.stat.is_strong_stop=this.kag.menu.snap.stat.is_strong_stop;if(this.kag.stat.is_skip==true&&this.kag.stat.is_strong_stop==false)this.kag.ftag.nextOrder()}else if(auto_next=="stop")this.kag.ftag.startTag("s",{"val":{}})}}};
tyrano.plugin.kag.tag.text={cw:true,pm:{"val":"","type":"add"},start:function(pm){if(this.kag.stat.is_script==true){this.kag.stat.buff_script+=pm.val+"\n";this.kag.ftag.nextOrder();return}this.kag.stat.current_message_str=pm.val;this.kag.stat.is_adding_text=false;this.kag.stat.is_click_text=false;this.kag.ftag.startTag("vr_message",{"val":pm.val});return},nextOrder:function(){},test:function(){}};
tyrano.plugin.kag.tag.label={pm:{nextorder:"true"},start:function(pm){if(this.kag.config.autoRecordLabel=="true"){var sf_tmp="trail_"+this.kag.stat.current_scenario.replace(".ks","").replace(/\u002f/g,"").replace(/:/g,"").replace(/\./g,"");var sf_buff=this.kag.stat.buff_label_name;var sf_label=sf_tmp+"_"+pm.label_name;if(this.kag.stat.buff_label_name!=""){if(!this.kag.variable.sf.record)this.kag.variable.sf.record={};var sf_str="sf.record."+sf_buff;var scr_str=""+sf_str+" = "+sf_str+"  || 0;"+sf_str+
"++;";this.kag.evalScript(scr_str)}if(this.kag.variable.sf.record)if(this.kag.variable.sf.record[sf_label])this.kag.stat.already_read=true;else this.kag.stat.already_read=false;this.kag.stat.buff_label_name=sf_label}if(pm.nextorder=="true")this.kag.ftag.nextOrder()}};
tyrano.plugin.kag.tag.config_record_label={pm:{color:"",skip:""},start:function(pm){var that=this;if(pm.color!=""){this.kag.config.alreadyReadTextColor=pm.color;this.kag.ftag.startTag("eval",{"exp":"sf._system_config_already_read_text_color = "+pm.color})}if(pm.skip!=""){if(pm.skip=="true")this.kag.config.unReadTextSkip="true";else this.kag.config.unReadTextSkip="false";this.kag.ftag.startTag("eval",{"exp":"sf._system_config_unread_text_skip = '"+pm.skip+"'"})}this.kag.ftag.nextOrder()}};
tyrano.plugin.kag.tag.p={cw:true,start:function(){var that=this;this.kag.stat.flag_ref_page=true;this.kag.ftag.showNextImg()}};tyrano.plugin.kag.tag.jump={pm:{storage:null,target:null,countpage:true},start:function(pm){var that=this;setTimeout(function(){that.kag.ftag.nextOrderWithLabel(pm.target,pm.storage)},1)}};tyrano.plugin.kag.tag.s={start:function(){this.kag.stat.is_strong_stop=true;this.kag.layer.hideEventLayer()}};
tyrano.plugin.kag.tag._s={vital:[],pm:{},start:function(pm){this.kag.stat.strong_stop_recover_index=this.kag.ftag.current_order_index;this.kag.ftag.nextOrder()}};
tyrano.plugin.kag.tag.wait={vital:["time"],pm:{time:0},start:function(pm){var that=this;this.kag.stat.is_strong_stop=true;this.kag.stat.is_wait=true;this.kag.layer.hideEventLayer();that.kag.tmp.wait_id=setTimeout(function(){that.kag.stat.is_strong_stop=false;that.kag.stat.is_wait=false;that.kag.layer.showEventLayer();that.kag.ftag.nextOrder()},pm.time)}};
tyrano.plugin.kag.tag.wait_cancel={vital:[],pm:{},start:function(pm){var that=this;clearTimeout(this.kag.tmp.wait_id);this.kag.tmp.wait_id="";this.kag.stat.is_strong_stop=false;this.kag.stat.is_wait=false;this.kag.layer.showEventLayer();this.kag.ftag.nextOrder()}};
tyrano.plugin.kag.tag.font={pm:{},log_join:"true",start:function(pm){this.kag.setMessageCurrentSpan();var new_font={};if(pm.size)this.kag.stat.font.size=pm.size;if(pm.color)this.kag.stat.font.color=$.convertColor(pm.color);if(pm.bold)this.kag.stat.font.bold=$.convertBold(pm.bold);if(pm.face)this.kag.stat.font.face=pm.face;if(pm.italic)this.kag.stat.font["italic"]=$.convertItalic(pm.italic);if(pm.edge)if(pm.edge=="none"||pm.edge=="")this.kag.stat.font.edge="";else this.kag.stat.font.edge=$.convertColor(pm.edge);
if(pm.shadow)if(pm.shadow=="none"||pm.shadow=="")this.kag.stat.font.shadow="";else this.kag.stat.font.shadow=$.convertColor(pm.shadow);this.kag.ftag.nextOrder()}};
tyrano.plugin.kag.tag.deffont={pm:{},start:function(pm){var new_font={};if(pm.size)this.kag.stat.default_font.size=pm.size;if(pm.color)this.kag.stat.default_font.color=$.convertColor(pm.color);if(pm.bold)this.kag.stat.default_font.bold=$.convertBold(pm.bold);if(pm.face)this.kag.stat.default_font.face=pm.face;if(pm.italic)this.kag.stat.default_font.italic=$.convertItalic(pm.italic);if(pm.edge)if(pm.edge=="none"||pm.edge=="")this.kag.stat.default_font.edge="";else this.kag.stat.default_font.edge=$.convertColor(pm.edge);
if(pm.shadow)if(pm.shadow=="none"||pm.shadow=="")this.kag.stat.default_font.shadow="";else this.kag.stat.default_font.shadow=$.convertColor(pm.shadow);this.kag.ftag.nextOrder()}};tyrano.plugin.kag.tag.nowait={pm:{},start:function(pm){this.kag.stat.is_nowait=true;this.kag.ftag.nextOrder()}};tyrano.plugin.kag.tag.endnowait={pm:{},start:function(pm){this.kag.stat.is_nowait=false;this.kag.ftag.nextOrder()}};
